WIP: [IIDM v1.4] Add ThreadLocalMultipleVariantContext (#183)
powsybl/powsybl-iidm4cpp pull request #277
Opened 2021-02-17 10:51 UTC by sebalaig

Signed-off-by: Sébastien LAIGRE <slaigre@silicom.fr>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#183 

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2021-02-17 11:11 UTC, sebalaig commented on src/iidm/ThreadLocalMultipleVariantContext.cpp
> +void ThreadLocalMultipleVariantContext::reset() {
This function exists in java but not called. It should probably be removed;

2021-03-08 15:04 UTC, mathbagu requested changes

2021-03-08 15:04 UTC, mathbagu commented on src/iidm/VariantManager.cpp
> +        m_variantContext.reset(newVariantContext.release());
Use the assignment operator or the swap method instead?

2021-03-08 15:04 UTC, mathbagu commented on test/iidm/CMakeLists.txt
> +target_link_libraries(unit-tests-iidm PRIVATE iidm-tests Threads::Threads)
I think this should be add to the IIDM library instead and then inherited by the other targets?

2021-03-08 15:04 UTC, mathbagu commented on test/iidm/VariantManagerTest.cpp
> +#include <iostream>
Remove this include

2021-03-15 18:25 UTC, mathbagu approved these changes

2021-03-15 18:25 UTC, merged